django/conf/project_template/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

ideas/urls.py
from django.conf.urls.defaults import *


from ideas.models import Idea

from ideas.views import *
from ideas.ideas_helpers import get_idea_from_id, dual_format


public_idea_dual = dual_format('idea_form.html')
#new_idea_decorator = dual_format('idea_form_top.html')


urlpatterns = patterns('',
    # Authenticated users urls                 
    url(r'^new/$', requires_login(new_idea), 
        { 'template_name' : 'idea_form.html' }, name="new-top-idea"),
    url(r'^idea/(?P<id>\d+)/add/$', requires_login(get_idea_from_id(new_children_idea)), 
        { 'template_name' : 'idea_form.html' }, name="new-children-idea"),
    url(r'^idea/(?P<id>\d+)/del/$', requires_login(get_idea_from_id(delete_idea)), name="delete-idea"),
    url(r'^idea/(?P<id>\d+)/edit/$', requires_login(get_idea_from_id(edit_idea)), name="edit-idea"),
    (r'^idea/(?P<id>\d+)/collaboration/$', requires_login(idea_collab)),
    (r'^idea/(?P<id>\d+)/make-public/$', requires_login(make_idea_public)),
    url(r'^shared/$', requires_login(show_shared_ideas), name="show-shared-ideas"),
    #url(r'^public/new/$', requires_login(new_public_idea), name="new-public-idea"),
    url(r'^public/new/$', public_idea_dual(requires_login(new_public_idea)), name="new-public-idea"),
    
    #public urls
    url(r'^public/$', show_public_ideas, name="show-public-ideas"),
    url(r'^idea/(?P<id>\d+)/$', get_idea_from_id(show_idea), name="show-idea"),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

from django.views.generic.simple import direct_to_template

import ideas
from ideas import views

from about.views import about_pages
from ideas.views import requires_login

from registration.forms import RegistrationFormUniqueEmail

from api.resources import IdeaResource, UserResource, PublicIdeaResource, FavoriteIdeaResource
from tastypie.api import Api

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(IdeaResource(), canonical=True)
v1_api.register(PublicIdeaResource())
v1_api.register(FavoriteIdeaResource())


admin.autodiscover()

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    (r'^accounts/register/$', 'registration.views.register', {'form_class' : RegistrationFormUniqueEmail, 'backend':'registration.backends.default.DefaultBackend' }),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    (r'^admin/', include(admin.site.urls)),
    ('^$', 'views.main_page'),
    (r'^about/$', direct_to_template, {'template' : 'about.html'}),
    (r'^about/(\w+)/$', about_pages),
    (r'^', include('ideas.urls')),
    (r'^', include('contactus.urls')),
    (r'^', include('friends.urls')),
    url(r'^api/', include(v1_api.urls)),
    
    (r'^home/$', 'views.main_backbone'),
    (r'^angular/$', 'app.views.angular_view')
    
)

ideas/models.py
from django.db import models
from django.contrib.auth.models import User
from djangotoolbox.fields import ListField
from django import forms
from django.forms import ModelForm

from django.core.urlresolvers import reverse
from django.contrib.contenttypes import generic

from friends.fields import ModelListField

from favorites.models import FavoriteItem

from django.db import IntegrityError

import datetime

    
class IdeaManager(models.Manager):
    
    def pagination_by_date(self, items_per_page, page, *args, **kwargs):
        return self.order_by('modified_date').reverse()[items_per_page*(page-1):page*items_per_page]
    
    def get_public_ideas(self):
        return self.filter(public=True).order_by('modified_date').reverse()
    
    #filter(owner=current_user, parent=None).
    def title_count(self, keyword):
        return self.filter(title__icontains=keyword).count()
    
class Category(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True)
    name = models.CharField(max_length=30)
    
    created_date = models.DateTimeField(default=datetime.datetime.today())
    modified_date = models.DateTimeField(default=datetime.datetime.today())
    
    def get_absolute_url(self):
        return "/categories/%i/" % self.id
    
    def get_del_url(self):
        return self.get_absolute_url() + "del/"
    
    def __unicode__(self):
        return self.name
    
class Idea(models.Model): 
    owner = models.ForeignKey(User, null=True, blank=True)
    title = models.CharField(max_length=30)
    text = models.CharField(max_length=140) 
    parent = models.ForeignKey('self', blank=True, null=True)
    #category = models.ForeignKey(Category, blank=True, null=True)
    
    public = models.BooleanField(default=False)
    
    created_date = models.DateTimeField(default=datetime.datetime.today())
    modified_date = models.DateTimeField(default=datetime.datetime.today())

    contributors = ModelListField(models.ForeignKey(User), null=True, blank=True)

    
    objects = IdeaManager()
    
    # Not protected against loops where idea has children and one of its children is 
    # its parent. Should be a way to avoid this.
    def get_children_count(self):
        count = self.idea_set.count()    
        for idea in self.idea_set.all():
            count += idea.get_children_count()
        return count 
    
    def get_contributors(self):
        result_list = []
        if self.contributors:
            for id in self.contributors:
                result_list += User.objects.filter(pk__exact=id)
        return result_list
    
    def is_original_owner(self, user):
        if self.owner and self.owner == user:
            return True
        elif self.parent:
            return self.parent.is_original_owner(user)
        else: 
            return False
        
    def is_contributor(self, user_primary_key):
        if self.contributors and user_primary_key in self.contributors:
            return True
        elif self.parent:
            return self.parent.is_contributor(user_primary_key)
        else:
            return False
        
    def is_parent_a_child(self, parent):
        for idea in self.idea_set.all():
           if idea == parent:
               return True
           else:
               return idea.is_parent_a_child(parent)
           
        return False
        
    def clean(self, *args, **kwargs):
        from django.core.exceptions import ValidationError
        
        if self.id and hasattr(self, 'parent'):
            if self.parent == self:
                raise ValidationError("Idea cannot be parent of itself.")
            
            if self.is_parent_a_child(self.parent):
                raise ValidationError("Idea child cannot be a parent")

        super(Idea, self).clean(*args, **kwargs)
        
    def full_clean(self, *args, **kwargs):
        return self.clean(*args, **kwargs)     
        
            
    def save(self, *args, **kwargs):
       ''' On save, update timestamps '''
       import sys
       print >>sys.stderr, 'Saving ' + self.title
       
       self.full_clean() 
       
       
       if not self.id:
            self.created_date = datetime.datetime.today()
       self.modified_date = datetime.datetime.today()
       
       
       
       if not self.parent is None:
           if hasattr(self.parent, 'modified_date'):
               self.parent.modified_date = datetime.datetime.today()
               self.parent.save()
       super(Idea, self).save(*args, **kwargs)
    
       
        
    def delete(self, **kwargs):
        self.idea_set.all().delete() 
        super(Idea, self).delete()
             
    
    def get_absolute_url(self):
        return reverse('show-idea', args=(self.pk,))
    
    def get_add_url(self):
        return reverse('new-children-idea', args=(self.pk,))
    
    def get_del_url(self):
        return reverse('delete-idea', args=(self.pk,))
    
    def get_edit_url(self):
        return reverse('edit-idea', args=(self.pk,))
    
    @property
    def add_url(self):
        return reverse('new-children-idea', args=(self.pk,))
    
    @property
    def del_url(self):
        return reverse('delete-idea', args=(self.pk,))
    
    @property
    def edit_url(self):
        return reverse('edit-idea', args=(self.pk,))
    
    # Update the last two urls to reverse style.
    def get_add_collab_url(self):
        return self.get_absolute_url() + "collaboration/"
    
    def get_make_public_url(self):
        return self.get_absolute_url() + "make-public/"
    
    def get_all_children(self, include_self=True):
        r = []
        if include_self:
            r.append(self)
        for c in Idea.objects.filter(parent=self):
            r.append(c.get_all_children(include_self=False))
        return r
    
    def __unicode__(self):
        return self.title
    
class IdeaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(IdeaForm, self).__init__(*args, **kwargs)
        self.fields['contributors'].widget.choices = [(i.pk, i) for i in User.objects.all()]
        if self.instance.pk:
            self.fields['contributors'].initial = self.instance.contributors
    class Meta:
        model = Idea
 
 

class Favorite(models.Model):
    owner = models.ForeignKey(User)
    favorite_idea = models.ForeignKey(Idea)
    
    class Meta:
        unique_together = (("owner", "favorite_idea"),)
     
    def clean(self, *args, **kwargs):
        from django.core.exceptions import ValidationError
        
        if not hasattr(self, 'favorite_idea'):
            raise ValidationError("Favorite needs you to provide favorite_idea field")
        
        if not hasattr(self, 'owner'):
            raise ValidationError("Favorite needs owner field")
        
        if self.favorite_idea.owner == self.owner:
            raise ValidationError("Cannot favorite your own idea")
        
        if Favorite.objects.filter(owner=self.owner, favorite_idea=self.favorite_idea).exists():
            raise IntegrityError("Cannot favorite the same idea twice.") 
        
        if not self.favorite_idea.public:
            raise ValidationError("Cannot favorite private idea.") 

        super(Favorite, self).clean(*args, **kwargs)
        
    def full_clean(self, *args, **kwargs):
        return self.clean(*args, **kwargs) 
         
        
    def save(self, *args, **kwargs):
        self.full_clean()

        super(Favorite, self).save(*args, **kwargs)

ideas/forms.py
from django import forms
from django.forms import ModelForm
from ideas.models import Favorite, Idea

# A simple contact form with four fields.
class ContributorForm(forms.Form):
    email = forms.EmailField()

class IdeaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        owner = kwargs.pop("owner", None)  
        
        super(IdeaForm, self).__init__(*args, **kwargs)
        
        self.fields['title'].required = True
        self.fields['title'].max_length = 30
        self.fields['text'].error_messages = {'required' : 'Please enter text'}
        self.fields['title'].error_messages = {'required': 'Please enter title'}
        self.fields['text'].max_length = 140
        self.fields['public'].label = 'Would you like to make the idea public?'
        
        
    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 5:
            raise forms.ValidationError("Title needs to have more than 4 characters")
        return title
        
    def clean_text(self):
        text = self.cleaned_data['text']
        num_words = len(text)
        if num_words < 10:
            raise forms.ValidationError("Text needs to have more than 9 characters!")
        return text
    
    class Meta:
        model = Idea
        fields = ('title', 'text', 'public')
        widgets = {
            'text': forms.Textarea(attrs={'cols': 20, 'rows': 10, 'maxlength': 140}),
        }

    
class FavoriteForm(forms.ModelForm):
    class Meta:
        model = Favorite 
        fields = ('favorite_idea', 'owner')
#===============================================================================
# class CategoryForm(forms.ModelForm):
#    
#    def __init__(self, *args, **kwargs): 
#        super(CategoryForm, self).__init__(*args, **kwargs)
#        self.fields['name'].max_length = 30
#    
#    def clean_name(self):
#        text = self.cleaned_data['name']
#        if len(text) < 4:
#            raise forms.ValidationError("Category name has to be more than 3 letters") 
#        return text
#    
#    class Meta:
#        model = Category
#        fields = ['name']
#===============================================================================

ideas/templates/includes/basic_idea.html
{% load pagination %}

ideas/templates/includes/idea.html
{% load pagination %}
<div class="row">
	<div class="span8">
		<h3><a href="{{ idea.get_absolute_url }}">{{ idea.title|softwraphtml }}</a> {% if show_owner %} <small>by {{ idea.owner }}</small> {% else %}
		{% if idea.public %}<span class="label label-info">Public</span> {% endif %}
		{% if idea.contributors %}<span class="label label-success">Shared</span> {% endif %} {% endif %}</h3>
		<p>
			{{ idea.text|softwraphtml }}
		</p>
		{% if show_contributors %}
		{% if idea.get_contributors %}
		<p>
			<h4>Contributors: <small> {% for contrib in idea.get_contributors %} {{ contrib.username }} {% endfor %}</small></h4>
		</p>
		{% endif %}
		{% endif %}

		<p>
			{% if idea.owner == request.user %}
			<!-- Owner buttons -->
			{% include "includes/idea_owner_links.html" with idea=idea %}
			{% else %}
			<!-- Buttons for contributor -->
			{% include "includes/idea_contributors_links.html" with idea=idea %}
			{% endif %}
		</p>
	</div>
	<div class="span1 offset2">
		<p style='text-align: right; size: 20em'>
		</br>
			<span class="badge badge-info">{{ idea.get_children_count }}</span>
		</p>
		
	</div>
</div>

ideas/templates/includes/idea_contributors_links.html
<!-- You have to include and use with to pass the idea -->
<a href="{{ idea.get_add_url }}">New</a> | 
<a href="{{ idea.get_edit_url }}">Edit</a>

ideas/templates/includes/idea_modal.html
{% load bootstrap_toolkit %}
<script>


	window.onload = function() {
		// Listener to reset defaults when modal closes
		$('body').on('hidden', '#IdeaModal', function() {

			console.log('we have hidden the modal');
			// Clear all the fields
			$('#id_title').val('');
			$('#id_text').val('');

			$('#idea_error_field').empty()

			$('#id_public').removeAttr('checked');

			$('#id_parent').val(null);
			$('#id_idea_pk').val(null)

		});

	}
	/*function newIdea() {
	 var url = "{% url api_dispatch_list resource_name='idea' api_name='v1' %}"
	 // Add form validation
	 var form = document.forms[0];
	 var title = form.elements["id_title"];
	 var text = form.elements['id_text'];

	 $.ajax({
	 type : "POST",
	 url : url,
	 accepts : 'application/json',
	 contentType : "application/json",
	 data : JSON.stringify({
	 "title" : title.value,
	 "text" : text.value
	 }),
	 //dataType : "application/json",
	 //processData : false,
	 error : function(jq, textStatus, errorThrown) {
	 var error = $.parseJSON(jq.responseText);
	 var idea = error.idea;

	 var isTitleError = typeof idea.title != 'undefined';
	 var isTextError = typeof idea.text != 'undefined';

	 if (isTitleError || isTextError) {
	 var error_field = document.getElementById('form_error_field');
	 error_field.innerHTML = "<h5>Errors:</h5><ul>";

	 if (isTitleError) {
	 error_field.innerHTML = error_field.innerHTML + "<li>" + idea.title + "</li>";
	 }
	 if (isTextError) {
	 error_field.innerHTML = error_field.innerHTML + "<li>" + idea.text + "</li>";
	 }

	 error_field.innerHTML = error_field.innerHTML + "</ul>";

	 }

	 },
	 contentType : "application/json",
	 success : function(result) {
	 alert("Idea created");
	 }
	 });
	 }
	 */

</script>

<!-- Modal -->
<div id="IdeaModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			×
		</button>
		<h3 id="myModalLabel">New Idea</h3>
	</div>
	<div class="modal-body">
		<div id="idea_error_field"></div>
		<form class="modal-form">
			{% csrf_token %}
			{{ form|as_bootstrap }}
			<!-- Extra fields of the form like parent -->
			<input type="hidden" id="id_idea_pk" name="id_idea_pk">
			<input type="hidden" id="id_parent" name="id_parent">

		</form>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">
			Close
		</button>
		<a href="#" id="submitIdea" class="btn btn-primary">Submit</a>
	</div>
</div>

ideas/templates/includes/idea_owner_links.html
<!-- You have to include and use with to pass the idea -->
<a href="{{ idea.add_url }}">New</a> | 
<a href="{{ idea.edit_url }}">Edit</a> |
<a href="{{ idea.del_url }}">Delete</a>

ideas/templates/includes/list_categories.html
{% if categories %}
<div id="categories_list">
	<table class="table table-striped">
		<tr>
			<th>Name</th>
			<th>Options</th>
		</tr>

		{% for category in categories %}
		<tr>
			<td>{{ category.name }}</td>

			<td>
			<div class="btn-group">
				<button class="btn btn-info" onclick="location.href='#';">
					Ideas
				</button>
				<button class="btn btn-danger" onclick="location.href='{{ category.get_del_url }}';">
					Delete
				</button>
			</div></td>
		</tr>
		{% endfor %}

	</table>
</div>
{% else %}
Currently you haven't created any categories.
{% endif %}

ideas/templates/includes/list_ideas.html
{% load pagination %}
{% if idea_list %}
	{% for idea in idea_list %}
	<div class="well well-small">
		{% include 'includes/idea.html' with idea=idea %}
	</div>
	{% endfor %}
{% else %}
	<p style='text-align: center;'> No ideas.</p>
{% endif %}	

ideas/templates/includes/list_public_ideas.html
{% if idea_list %}
{% load pagination %}
<div class="container">
	{% for idea in idea_list %}
	<div class="well well-small">
		<h3><a href="{{ idea.get_absolute_url }}">{{ idea.title }}</a> <small>by {{ idea.owner }}</small> </h3>
		<p>{{ idea.text }}</p>
		<button class="btn btn-primary">Share</button> | <a href="#">Favorite</a>
	</div>
	
	{% endfor %}
</div>
{% else %}
Currently there is no public ideas.

{% endif %}

ideas/templates/includes/list_shared_ideas.html
{% load pagination %}
<div class="container">
	{% for idea in idea_list %}
	<div class="well well-small">
		{% include "includes/idea.html" with show_contributors="True" show_owner="True" %}
	</div>
	{% endfor %}
</div>

ideas/templates/includes/new_category_form.html
{% load bootstrap_toolkit %}
<form class="form-{{ layout }}" action="" method="post">
	{% csrf_token %}
	<div class="span4">
		{{ form|as_bootstrap:layout }}
	</div>
	<div span="span4">
		<button type="submit" class="btn btn-primary">
			New Category
		</button>
	</div>
	
</form>

ideas/templates/includes/new_idea_modal.html
{% load bootstrap_toolkit %}
<script>
	/*function newIdea() {
		var url = "{% url api_dispatch_list resource_name='idea' api_name='v1' %}"
		// Add form validation
		var form = document.forms[0];
		var title = form.elements["id_title"];
		var text = form.elements['id_text'];

		$.ajax({
			type : "POST",
			url : url,
			accepts : 'application/json',
			contentType : "application/json",
			data : JSON.stringify({
				"title" : title.value,
				"text" : text.value
			}),
			//dataType : "application/json",
			//processData : false,
			error : function(jq, textStatus, errorThrown) {
				var error = $.parseJSON(jq.responseText);
				var idea = error.idea;

				var isTitleError = typeof idea.title != 'undefined';
				var isTextError = typeof idea.text != 'undefined';

				if (isTitleError || isTextError) {
					var error_field = document.getElementById('form_error_field');
					error_field.innerHTML = "<h5>Errors:</h5><ul>";

					if (isTitleError) {
						error_field.innerHTML = error_field.innerHTML + "<li>" + idea.title + "</li>";
					}
					if (isTextError) {
						error_field.innerHTML = error_field.innerHTML + "<li>" + idea.text + "</li>";
					}
					
					error_field.innerHTML = error_field.innerHTML + "</ul>";

				}

			},
			contentType : "application/json",
			success : function(result) {
				alert("Idea created");
			}
		});
		}
		*/
	
</script>
<!-- Button to trigger modal -->
<a href="#newIdeaModal" role="button" class="btn btn-primary" data-toggle="modal">New Idea</a>

<!-- Modal -->
<div id="newIdeaModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			×
		</button>
		<h3 id="myModalLabel">New Idea</h3>
	</div>
	<div class="modal-body">
		<div id="idea_error_field"></div>
		<form class="modal-form">
			{% csrf_token %}
			{{ form|as_bootstrap }}
			<!-- Extra fields of the form like parent -->
			<input type="hidden" id="idea_parent" name="idea_parent" value=null>
			
		</form>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">
			Close
		</button>
		<a href="#" id="createNewIdea" class="btn btn-primary">Submit</a>
	</div>
</div>

ideas/templates/includes/show_top_ideas.html
<div class="container container-fluid">
	<div class="well">
		<h1>Ideas</h1>
		<p>
			These are your ideas. You can branch out and have more ideas.
		</p>
		<p>
			{# Add new-idea button#}
			{#   #}
			<a href="{% url new-top-idea %}" role="button" class="btn btn-primary">New Idea</a>

			{# Temporary thing #}
			
			<!--
			<button onclick="addIdea('hjkfhe','klwfel')" class="btn btn-danger">
				Boo
			</button>-->
		</p>
	</div>

	<!-- Tabs -->

	{% include "includes/idea_nav.html" with active=1 %}

	<div id="idea_list" class="container">
		{% if idea_list %}
		{% include "includes/list_ideas.html" %}
		{% else %}
		<p id="no_ideas_paragraph" style='text-align: center;'>
			Currently no ideas.
		</p>
		{% endif %}
	</div>
</div>

<script>
	function addIdea(title, text) {
		var idea_list = document.getElementById('idea_list');
		idea_list.innerHTML = "<div class='well'>blah</div>" + idea_list.innerHTML;

		var no_ideas_paragraph = document.getElementById('no_ideas_paragraph');
		if (no_ideas_paragraph != null) {
			// exists.
			no_ideas_paragraph.parentNode.removeChild(no_ideas_paragraph);
		}
	}
</script>

ideas/templates/includes/top_idea.html
{% load pagination %}
<div class="hero-unit">

	<h1>{{ parent_idea.title|softwraphtml }}</h1>
	<p>
		{{ parent_idea.text|softwraphtml }}
	</p>

	<!-- Owner controls -->
	{% if rights == "owner" %}
	<p style="text-align: left;">
		<button class="btn btn-primary" onclick="location.href='{{ parent_idea.get_add_url }}';">
			New Idea
		</button>

		<button class="btn btn-success" onclick="location.href='{{ parent_idea.get_edit_url }}';">
			Edit Idea
		</button>

		<button class="btn btn-danger" onclick="location.href='{{ parent_idea.get_del_url }}';">
			Delete Idea
		</button>

		{% if parent_idea.parent %}
		<button class="btn btn-info" onclick="location.href='{{ parent_idea.parent.get_absolute_url }}';">
			Previous Idea
		</button>

		{% else %}
		<button class="btn btn-info" onclick="location.href='/';">
			See All Ideas
		</button>

		{% endif %}
	</p>
	{% endif %}
	<!-- Contributor controls -->
	{% if rights == "contributor" %}
	<p style="text-align: left;">
		<button class="btn btn-primary" onclick="location.href='{{ parent_idea.get_add_url }}';">
			New Idea
		</button>

		<button class="btn btn-success" onclick="location.href='{{ parent_idea.get_edit_url }}';">
			Edit Idea
		</button>

		{% if parent_idea.parent %}
		<button class="btn btn-info" onclick="location.href='{{ parent_idea.parent.get_absolute_url }}';">
			Previous Idea
		</button>

		{% else %}
		<button class="btn btn-info" onclick="location.href='/shared/';">
			See All Ideas
		</button>

		{% endif %}
	</p>
	{% endif %}
	
	<!-- Public controls --> 
	{% if rights == "public" %}

	{% endif %}

</div>